import test from "node:test";import assert from "node:assert/strict";import {compound,equalWeightReturn,fundingReturn,turnover,maxDrawdown,resolvePaperSnapshot} from "./portfolio";import {summarizeForward} from "./forward-stats";import {appendSnapshot,readSnapshots,type Snapshot} from "./ranking-store";import {fetchRankingMarkets,schedule} from "./ranking-data";import {mkdtemp,rm,writeFile,readFile} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";

test("portfolio compounds weekly returns and computes one equal-weight return",()=>{assert.ok(Math.abs(compound(100,[.1,-.1])-99)<1e-12);assert.ok(Math.abs(equalWeightReturn([.1,.2,-.1,0])-.05)<1e-12);assert.equal(maxDrawdown([100,110,99,120,90]),.25)});
test("turnover charges membership changes only",()=>{assert.equal(turnover(["A","B","C","D"],["A","B","C","D"]),0);assert.equal(turnover(["A","B","C","D"],["A","B","C","E"]),.5)});
test("funding uses mark notional relative to entry and LONG direction",()=>{assert.ok(Math.abs(fundingReturn([{rate:.01,mark:110}],100)+.011)<1e-12);assert.ok(Math.abs(fundingReturn([{rate:-.01,mark:110}],100)-.011)<1e-12)});
test("resolver prices top4 and benchmark at identical opens with funding and turnover",()=>{const universe=["A","B","C","D","E"];const entry=Object.fromEntries(universe.map(x=>[x,100]));const exit={A:110,B:120,C:90,D:100,E:105};const result=resolvePaperSnapshot({universe,top4:["A","B","C","D"],previousTop4:["A","B","C","E"],entryPrices:entry,exitPrices:exit,funding:{A:-1,B:0,C:0,D:0,E:0},roundTripCostPct:.14});assert.ok(Math.abs(result.strategyReturnPct-4.68)<1e-9);assert.ok(Math.abs(result.benchmarkReturnPct-4.8)<1e-9);assert.ok(Math.abs(result.excessReturnPct+.12)<1e-9);assert.equal(result.turnover,.5)});
test("forward stats are weekly, checkpointed, and breadth descriptive",()=>{const s=summarizeForward([{status:"RESOLVED",strategyReturnPct:10,benchmarkReturnPct:5,excessReturnPct:5,breadth:.7},{status:"MISSED"} as any]);assert.equal(s.resolvedWeeks,1);assert.ok(Math.abs(s.strategyEquity-110)<1e-12);assert.equal(s.label,"PENGUMPULAN DATA");assert.equal(s.counts.MISSED,1)});
function snap(over:Partial<Snapshot>={}):Snapshot{return {schemaVersion:1,key:"2026-W35-x",specHash:"x",status:"OPEN",scheduledAt:1,formedAt:1,dataAsOf:1,entryAt:2,exitAt:3,universe:Array.from({length:16},(_,i)=>`C${i}`),lookbackReturns:{},ranking:[],top4:[],breadth:.5,ema200:{},signalPrices:{},dataQuality:{complete:true,errors:[]},...over}}
test("snapshot store is append-only, idempotent, immutable, concurrent-safe, and explicit on corruption",async()=>{const d=await mkdtemp(join(tmpdir(),"rank-"));try{const p=join(d,"x.jsonl");const first=await Promise.all(Array.from({length:12},()=>appendSnapshot(snap(),p)));assert.equal(first.filter(x=>x.created).length,1);assert.equal((await readFile(p,"utf8")).trim().split("\n").length,1);assert.equal((await appendSnapshot(snap(),p)).created,false);await assert.rejects(()=>appendSnapshot(snap({formedAt:2}),p));const resolved=snap({status:"RESOLVED",entryPrices:{C0:1},exitPrices:{C0:2},strategyReturnPct:1,benchmarkReturnPct:.5,excessReturnPct:.5});const resolutions=await Promise.all(Array.from({length:12},()=>appendSnapshot(resolved,p)));assert.equal(resolutions.filter(x=>x.created).length,1);assert.equal((await readFile(p,"utf8")).trim().split("\n").length,2);const rows=await readSnapshots(p);assert.equal(rows.length,1);assert.equal(rows[0].status,"RESOLVED");assert.equal(rows[0].formedAt,1);await assert.rejects(()=>appendSnapshot({...resolved,breadth:.9},p));await writeFile(p,"{bad\n");await assert.rejects(()=>readSnapshots(p),/corrupt/i)}finally{await rm(d,{recursive:true,force:true})}});
test("adapter backfills a short Binance page to exactly 1000 aligned closed bars",async()=>{const at=Date.UTC(2026,7,31,8),effective=at-1;let calls=0;const perSymbol=new Map<string,number>();const fetcher=async(url:any)=>{calls++;const symbol=new URL(String(url)).searchParams.get("symbol")!;const seen=(perSymbol.get(symbol)??0)+1;perSymbol.set(symbol,seen);const count=seen===1?974:26;const newest=seen===1?effective:effective-974*14400000;const raw=Array.from({length:count},(_,i)=>[0,"1","1","1",String(100+i),"1",newest-(count-1-i)*14400000]);return new Response(JSON.stringify(raw))};const r=await fetchRankingMarkets(effective,fetcher as typeof fetch);assert.equal(r.complete,true);assert.equal(r.markets[0].candles.length,1000);assert.equal(calls,32)});
test("adapter has Monday 08 UTC schedule, uses the just-closed 07:59:59.999 bar once",async()=>{const at=Date.UTC(2026,7,31,8),effective=at-1;assert.equal(schedule(at).scheduledAt,at);assert.equal(schedule(at).effectiveCloseAt,effective);const raw=Array.from({length:1000},(_,i)=>[0,"1","1","1",String(100+i),"1",effective-(999-i)*14400000]);let requested="";const fetcher=async(url:any)=>{requested=String(url);return new Response(JSON.stringify(raw))};const r=await fetchRankingMarkets(effective,fetcher as typeof fetch);assert.equal(r.complete,true);assert.equal(r.markets.length,16);assert.equal(r.markets[0].candles.length,1000);assert.match(requested,new RegExp(`endTime=${effective}`));assert.equal(r.effectiveRebalanceAt,at)});
