import { createHash } from "node:crypto";
import { FIXED_UNIVERSE, rankUniverse } from "./ranking";
import { fetchRankingMarkets, FORMATION_WINDOW_MS, schedule } from "./ranking-data";
import { appendSnapshot, readSnapshots, type Snapshot } from "./ranking-store";
import { resolvePaperSnapshot } from "./portfolio";
import { BINANCE, type Candle } from "./indicators";

export const SPEC_HASH = "02abfad675d23211de4af3f39c5bc011f465e5926a1337f635d178539d6ef48a";
const ROUND_TRIP_COST_PCT = Number(process.env.RANKING_ROUND_TRIP_COST_PCT ?? .14);

export function isoWeek(ms:number){const d=new Date(ms),x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return `${x.getUTCFullYear()}-W${String(Math.ceil((((x.getTime()-y.getTime())/86400000)+1)/7)).padStart(2,"0")}`}
export function snapshotKey(at:number,hash=SPEC_HASH){return `${isoWeek(at)}-${hash.slice(0,12)}`}
export function requestAllowed(req:Request){const origin=req.headers.get("origin"),host=req.headers.get("host");if(!origin||!host)return false;try{if(new URL(origin).host!==host)return false}catch{return false}const token=process.env.RANKING_SNAPSHOT_TOKEN;if(token&&req.headers.get("authorization")!==`Bearer ${token}`)return false;return true}
export async function preview(now=Date.now()){const s=schedule(now),data=await fetchRankingMarkets(s.effectiveCloseAt),ranking=rankUniverse(data.markets,s.effectiveCloseAt);return{mode:"PREVIEW_LIVE",...s,...data,ranking,specHash:SPEC_HASH}}
export async function formSnapshot(now=Date.now()){const s=schedule(now);if(now<s.scheduledAt||now>s.scheduledAt+FORMATION_WINDOW_MS)throw new Error("Outside bounded formation window; missed weeks cannot be backfilled");const p=await preview(now);if(!p.complete||p.ranking.status!=="COMPLETE")throw new Error(`INCOMPLETE: ${[...p.errors,...(p.ranking.status==="INCOMPLETE"?p.ranking.errors:[])].join("; ")}`);const r=p.ranking;const snap:Snapshot={schemaVersion:1,key:snapshotKey(s.scheduledAt),specHash:SPEC_HASH,status:"OPEN",scheduledAt:s.scheduledAt,formedAt:now,dataAsOf:r.dataAsOf,entryAt:s.entryAt,exitAt:s.exitAt,universe:[...FIXED_UNIVERSE],lookbackReturns:r.lookbackReturns,ranking:r.ranking,top4:r.top4,breadth:r.breadth,ema200:r.ema200,signalPrices:r.signalPrices,dataQuality:{complete:true,errors:[]}};return appendSnapshot(snap)}

async function priceAtOpen(symbol:string,at:number,fetcher:typeof fetch){const url=`${BINANCE}/fapi/v1/klines?symbol=${symbol}USDT&interval=4h&startTime=${at}&limit=1`;const r=await fetcher(url,{cache:"no-store",signal:AbortSignal.timeout(10_000)});if(!r.ok)throw new Error(`${symbol} open HTTP ${r.status}`);const rows=await r.json() as Candle[];if(!rows.length||Number(rows[0][0])!==at)throw new Error(`${symbol}: exact 4h open unavailable at ${at}`);return Number(rows[0][1])}
async function fundingPct(symbol:string,start:number,end:number,entry:number,fetcher:typeof fetch){const url=`${BINANCE}/fapi/v1/fundingRate?symbol=${symbol}USDT&startTime=${start}&endTime=${end-1}&limit=1000`;const r=await fetcher(url,{cache:"no-store",signal:AbortSignal.timeout(10_000)});if(!r.ok)throw new Error(`${symbol} funding HTTP ${r.status}`);const rows=await r.json() as {fundingRate:string;markPrice:string}[];return -100*rows.reduce((sum,x)=>sum+Number(x.fundingRate)*Number(x.markPrice)/entry,0)}

export async function resolveOpenSnapshots(now=Date.now(),fetcher:typeof fetch=fetch){const rows=await readSnapshots();for(let index=0;index<rows.length;index++){const open=rows[index];if(open.status!=="OPEN"||open.exitAt>now)continue;try{const entryPrices:Record<string,number>={},exitPrices:Record<string,number>={},funding:Record<string,number>={};for(let i=0;i<open.universe.length;i+=4){await Promise.all(open.universe.slice(i,i+4).map(async symbol=>{entryPrices[symbol]=await priceAtOpen(symbol,open.entryAt,fetcher);exitPrices[symbol]=await priceAtOpen(symbol,open.exitAt,fetcher);funding[symbol]=await fundingPct(symbol,open.entryAt,open.exitAt,entryPrices[symbol],fetcher)}))}const previous=[...rows].slice(0,index).reverse().find(x=>x.status==="RESOLVED")?.top4??[];const result=resolvePaperSnapshot({universe:open.universe,top4:open.top4,previousTop4:previous,entryPrices,exitPrices,funding,roundTripCostPct:ROUND_TRIP_COST_PCT});await appendSnapshot({...open,status:"RESOLVED",entryPrices,exitPrices,funding,...result})}catch{/* Keep OPEN and retry on a later request; never invent fills. */}}
}

export async function recordMissed(now=Date.now()){const s=schedule(now),key=snapshotKey(s.scheduledAt),rows=await readSnapshots();if(now<=s.scheduledAt+FORMATION_WINDOW_MS||rows.some(x=>x.key===key))return;const empty=Object.fromEntries(FIXED_UNIVERSE.map(x=>[x,0]));await appendSnapshot({schemaVersion:1,key,specHash:SPEC_HASH,status:"MISSED",scheduledAt:s.scheduledAt,formedAt:now,dataAsOf:s.effectiveCloseAt,entryAt:s.entryAt,exitAt:s.exitAt,universe:[...FIXED_UNIVERSE],lookbackReturns:{},ranking:[],top4:[],breadth:0,ema200:empty,signalPrices:empty,dataQuality:{complete:false,errors:["Formation window elapsed without an immutable OPEN snapshot"]}})}
export async function history(now=Date.now()){await recordMissed(now);await resolveOpenSnapshots(now);const rows=await readSnapshots();return{snapshots:rows,stats:(await import("./forward-stats")).summarizeForward(rows),specHash:SPEC_HASH}}
export function canonicalHash(text:string){return createHash("sha256").update(text).digest("hex")}
